spring:
  application:
    name: speechcoach
  datasource:
    url: jdbc:postgresql://localhost:5432/speechcoach
    driver-class-name: org.postgresql.Driver
    username: Oli
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

anthropic:
  api-key: ${ANTHROPIC_API_KEY}
